//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Calificacion_de_Estudiantes.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificaciones
    {
        public int CalificacionId { get; set; }
        public int EstudianteId { get; set; }
        public int MateriaId { get; set; }
        public Nullable<int> Calificacion1 { get; set; }
        public Nullable<int> Calificacion2 { get; set; }
        public Nullable<int> Calificacion3 { get; set; }
        public Nullable<int> Calificacion4 { get; set; }
        public Nullable<int> Examen { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Clasificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual Materias Materias { get; set; }
    }
}
