//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema_de_manejo_de_empleados.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int EmpleadoId { get; set; }
        public string Nombre { get; set; }
        public int DepartamentoId { get; set; }
        public int CargoId { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public decimal Salario { get; set; }
        public string Estado { get; set; }
    
        public virtual Cargos Cargos { get; set; }
        public virtual Departamentos Departamentos { get; set; }
    }
}
