//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Citas_para_Spa.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public int CitaId { get; set; }
        public int PacienteId { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public int ServicioId { get; set; }
        public int Duracion { get; set; }
        public int TerapeutaId { get; set; }
        public Nullable<int> DiasRestantes { get; set; }
        public string Estado { get; set; }
    
        public virtual Pacientes Pacientes { get; set; }
        public virtual Servicios Servicios { get; set; }
        public virtual Terapeutas Terapeutas { get; set; }
    }
}
