//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agencia_de_Tours.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tours
    {
        public int TourId { get; set; }
        public string Nombre { get; set; }
        public int PaisId { get; set; }
        public int DestinoId { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public decimal Precio { get; set; }
        public int DuracionDias { get; set; }
        public int DuracionHoras { get; set; }
        public Nullable<decimal> ITBIS { get; set; }
        public Nullable<System.DateTime> FechaHoraFin { get; set; }
        public string Estado { get; set; }
    
        public virtual Destinos Destinos { get; set; }
        public virtual Paises Paises { get; set; }
    }
}
